version: '3.7'

services:
  app-db:
    container_name: app-db
    build: db
    ports:
      - 27018:27017
    volumes:
      - ./db/data/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: app
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_USER_USERNAME: app-admin
      MONGO_INITDB_USER_PASSWORD:
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet

  app-backend:
    container_name: app-backend
    build: server
    volumes:
      - ./server/src:/app/src
      - ./server/config:/app/config
      - ./server/locales:/app/locales
      - ./server/public:/app/public
      - ./server/test:/app/test
    ports:
      - 8080:8080
    depends_on:
      - app-db
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NODE_APP_INSTANCE: docker
      MONGO_DB:
      WAIT_HOSTS: app-db:27017
    healthcheck:
      test: node healthcheck

  app-frontend:
    container_name: app-frontend
    build: client
    depends_on:
      - app-backend
    volumes:
      - ./client/api:/app/api
      - ./client/assets:/app/assets
      - ./client/components:/app/components
      - ./client/layouts:/app/layouts
      - ./client/locales:/app/locales
      - ./client/middleware:/app/middleware
      - ./client/pages:/app/pages
      - ./client/plugins:/app/plugins
      - ./client/static:/app/static
      - ./client/store:/app/store
      - ./client/test:/app/test
      - ./client/feathers-client.js:/app/feathers-client.js
      - ./client/nuxt.config.js:/app/nuxt.config.js
    ports:
      - 3000:3000
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      NODE_APP_INSTANCE: docker
      API_URL: http://app-backend:8080
      HOST: 0.0.0.0
      PORT: 3000
    healthcheck:
      test: node healthcheck
  # app-reverse-proxy:
  #   container_name: app-reverse-proxy
  #   image: nginx:alpine
  #   volumes:
  #     - ./server/public:/usr/share/nginx/backend:ro
  #     - ./client/assets:/usr/share/nginx/frontend:ro
  #     - ./proxy/site.conf:/etc/nginx/nginx.conf:ro
  #     - ./proxy/logs:/etc/nginx/logs:rw
  #     # - ./proxy/certs:/etc/nginx/certs:ro
  #     # - ./letsencrypt:/etc/letsencrypt:ro
  #   depends_on:
  #     - app-frontend
  #   ports:
  #     - 80:80
  #     - 443:443
